exports.fakeData = {
  details: [
    {
      id: '1',
      color: 'Blue',
      weight: 0.2,
      size: 'Small',
      fabric: 'Cotton',
    },
    {
      id: '2',
      color: 'Black',
      weight: 0.2,
      size: 'Small',
      fabric: 'Cotton',
    },
    {
      id: '3',
      color: 'Blue',
      weight: 0.2,
      size: 'Large',
      fabric: 'Cotton',
    },
    {
      id: '4',
      color: 'Black',
      weight: 0.2,
      size: 'Large',
      fabric: 'Cotton',
    },
    {
      id: '1',
      color: 'Blue',
      weight: 0.2,
      size: 'Small',
      fabric: 'Fiber',
    },
    {
      id: '2',
      color: 'Black',
      weight: 0.2,
      size: 'Small',
      fabric: 'Fiber',
    },
    {
      id: '3',
      color: 'Blue',
      weight: 0.2,
      size: 'Large',
      fabric: 'Fiber',
    },
    {
      id: '4',
      color: 'Black',
      weight: 0.2,
      size: 'Large',
      fabric: 'Fiber',
    },
  ],
};
