language: node_js
node_js:
  - node
cache:
  directories:
    - /node_modules # NPM packages
env:
  - BUILD_DIR=client
  - BUILD_DIR=server
script:
  - if [ "$BUILD_DIR" = "client" ]; then cd $BUILD_DIR && npm install && npm test && npm run build; fi
  - if [ "$BUILD_DIR" = "server" ]; then cd $BUILD_DIR && npm install && npm test; fi
